hikvision:
  callback:
    host: "0.0.0.0"
    port: 8099
    path: "/hikvision/callback"
    secret: "CHANGE_ME"

  devices:
    - name: "GA4818739"
      ip: "37.18.105.89"
      port: 80                # ISAPI HTTP порт
      protocol: "http"       # принудительно HTTP, не https
      ssl: false              # отключаем проверку SSL полностью
      username: "admin"
      password: "Ee40060840"
      mode: "callback"       # режим получения событий (callback предпочтительно)

  allowed_device_ids: []
